# Generated by Django 4.1.5 on 2023-02-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patients_age', models.IntegerField()),
                ('file_type', models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=100)),
                ('file', models.FileField(upload_to='raw/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('preprocessed_file_path', models.CharField(blank=True, max_length=100, null=True)),
                ('preprocessed_file_number', models.IntegerField(blank=True, null=True)),
                ('predicted_class', models.CharField(blank=True, max_length=100, null=True)),
                ('predicted_probas', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_images', models.CharField(blank=True, max_length=100, null=True)),
                ('overlayed_images', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.IntegerField(default=0)),
                ('predicted_class', models.CharField(max_length=100)),
                ('predicted_probas', models.CharField(max_length=500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patientinfo')),
            ],
        ),
    ]
