# Generated by Django 4.1.5 on 2023-01-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patients_name', models.CharField(max_length=100)),
                ('patients_age', models.IntegerField()),
                ('file_type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], max_length=100)),
                ('file', models.FileField(upload_to='endoscopy/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('predicted_class', models.CharField(blank=True, max_length=100, null=True)),
                ('predicted_probas', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_images', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
