# Generated by Django 4.1.5 on 2023-01-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='file_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], default='Image', max_length=100),
        ),
    ]
