# Generated by Django 4.1.5 on 2023-01-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_patientinfo_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='preprocessed_file_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='preprocessed_file_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='file',
            field=models.FileField(upload_to='raw/'),
        ),
    ]
