# Generated by Django 4.1.5 on 2023-04-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_patientinfo_predicted_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='other_details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
