# Generated by Django 4.1.5 on 2023-01-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_patientinfo_preprocessed_file_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='file',
            field=models.FileField(default='media/endoscopy/FDD.png', upload_to='raw/'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='patients_age',
            field=models.IntegerField(default='999'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='patients_name',
            field=models.CharField(default='Test', max_length=100),
        ),
    ]
