# Generated by Django 4.1.5 on 2023-01-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_patientinfo_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='file_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video')], default='image', max_length=100),
        ),
    ]
