# Generated by Django 4.1.5 on 2023-02-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_patientinfo_file_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinfo',
            old_name='patients_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='last_name',
            field=models.CharField(default='Test', max_length=100),
        ),
    ]
